package fixture;

import dev.gmitch215.bytebox.Env;
import dev.gmitch215.bytebox.ExecutionCtx;
import dev.gmitch215.bytebox.Handlers;
import dev.gmitch215.bytebox.Request;
import dev.gmitch215.bytebox.Response;
import dev.gmitch215.bytebox.MailMessage;
import dev.gmitch215.bytebox.QueueBatch;
import dev.gmitch215.bytebox.ScheduledController;
import dev.gmitch215.bytebox.TraceItem;
import dev.gmitch215.bytebox.durable.DurableHandlers;
import dev.gmitch215.bytebox.durable.DurableState;
import dev.gmitch215.bytebox.socket.WebSocket;
import org.teavm.jso.JSExport;
import org.teavm.jso.JSObject;
import org.teavm.jso.core.JSArrayReader;
import org.teavm.jso.core.JSPromise;
import org.teavm.jso.typedarrays.ArrayBuffer;

/**
 * The exported entry point, in its own class because a static `fetch` cannot sit beside the
 * interface's instance `fetch` on the handler itself. This is what the Gradle plugin generates.
 */
public final class Entry {

	private static final CoreWorker HANDLER = new CoreWorker();

	private Entry() {}

	@JSExport
	public static JSPromise<Response> fetch(Request request, Env env, ExecutionCtx ctx) {
		return Handlers.fetch(HANDLER, request, env, ctx);
	}

	// one export per trigger the handler implements, which is what the plugin derives from the
	// interfaces on the class
	@JSExport
	public static JSPromise<JSObject> scheduled(
		ScheduledController controller,
		Env env,
		ExecutionCtx ctx
	) {
		return Handlers.scheduled(HANDLER, controller, env, ctx);
	}

	@JSExport
	public static JSPromise<JSObject> email(MailMessage message, Env env, ExecutionCtx ctx) {
		return Handlers.email(HANDLER, message, env, ctx);
	}

	@JSExport
	public static JSPromise<JSObject> queue(QueueBatch batch, Env env, ExecutionCtx ctx) {
		return Handlers.queue(HANDLER, batch, env, ctx);
	}

	@JSExport
	public static JSPromise<JSObject> tail(
		JSArrayReader<TraceItem> events,
		Env env,
		ExecutionCtx ctx
	) {
		return Handlers.tail(HANDLER, events, env, ctx);
	}

	@JSExport
	public static JSPromise<JSObject> alarm(Env env, ExecutionCtx ctx) {
		return Handlers.alarm(HANDLER, env, ctx);
	}

	// what the plugin generates for a Durable Object: one export per method the runtime calls, each
	// taking the instance's identifier first so the Java object can be paired with the JavaScript one
	@JSExport
	public static JSPromise<Response> durableCounterFetch(
		String id,
		Request request,
		DurableState state,
		Env env
	) {
		return DurableHandlers.fetch(counter(id), request, state, env);
	}

	@JSExport
	public static JSPromise<JSObject> durableCounterAlarm(String id, DurableState state, Env env) {
		return DurableHandlers.alarm(counter(id), state, env);
	}

	@JSExport
	public static JSPromise<JSObject> durableCounterMessageText(
		String id,
		WebSocket socket,
		String text,
		DurableState state,
		Env env
	) {
		return DurableHandlers.message(counter(id), socket, text, state, env);
	}

	@JSExport
	public static JSPromise<JSObject> durableCounterMessageBytes(
		String id,
		WebSocket socket,
		ArrayBuffer bytes,
		DurableState state,
		Env env
	) {
		return DurableHandlers.message(counter(id), socket, bytes, state, env);
	}

	@JSExport
	public static JSPromise<JSObject> durableCounterClosed(
		String id,
		WebSocket socket,
		int code,
		String reason,
		boolean clean,
		DurableState state,
		Env env
	) {
		return DurableHandlers.closed(counter(id), socket, code, reason, clean, state, env);
	}

	@JSExport
	public static JSPromise<JSObject> durableCounterFailed(
		String id,
		WebSocket socket,
		String message,
		DurableState state,
		Env env
	) {
		return DurableHandlers.failed(counter(id), socket, message, state, env);
	}

	private static Counter counter(String id) {
		return DurableHandlers.instance(id, Counter::new);
	}

	public static void main(String[] args) {
		// what the generated ByteboxCodecs.register() does
		dev.gmitch215.bytebox.json.JSON.register(Order.class, new Order.OrderCodec());
		System.out.println("core fixture ready");
	}
}
