package fixture;

import dev.gmitch215.bytebox.Env;
import dev.gmitch215.bytebox.ExecutionCtx;
import dev.gmitch215.bytebox.Handlers;
import dev.gmitch215.bytebox.Request;
import dev.gmitch215.bytebox.Response;
import org.teavm.jso.JSExport;
import org.teavm.jso.core.JSPromise;

/**
 * The exported entry point, in its own class because a static `fetch` cannot sit beside the
 * interface's instance `fetch` on the handler itself. This is what the Gradle plugin generates.
 */
public final class Entry {

	private static final CoreWorker HANDLER = new CoreWorker();

	private Entry() {}

	@JSExport
	public static JSPromise<Response> fetch(Request request, Env env, ExecutionCtx ctx) {
		return Handlers.fetch(HANDLER, request, env, ctx);
	}

	public static void main(String[] args) {
		// what the generated ByteboxCodecs.register() does
		dev.gmitch215.bytebox.json.Json.register(Order.class, new Order.OrderCodec());
		System.out.println("core fixture ready");
	}
}
